config/routes.rb
Rails.application.routes.draw do
  # is it companies and amployees or contractor and company
  devise_for :companies,  controllers: { registrations: 'company/registrations', sessions: 'company/sessions' }
  devise_for :employees, controllers: { omniauth_callbacks: 'contractor/omniauth_callbacks', sessions: 'contractor/sessions' }
  resources :contractors, only: [:show]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :contractor do
    root to: 'cities#index', as: :root

    namespace :account do
      resource :profile, only: [:show, :edit, :update]
      resources :work_experiences, only: [:index, :new, :create, :show, :edit, :update]
      resources :job_applications, only: [:index]
    end

    resources :jobs, only: [:index, :show] do
      resources :job_applications, only: [:new, :create]
    end
  end

  namespace :company do
    root to: 'account/profiles#show', as: :root

    namespace :account do
      root to: 'profiles#show', as: :root

      resource :profile, only: [:show, :edit, :update]

      resources :jobs
      # ALL hence only: [:index, :show, :new, :create, :edit, :update, :destroy]

      resources :job_applications, only: [:show] do
        member do
          patch :accept
          patch :decline
        end
      end
    end
  end

  # static pages
  get '/i-am-a-company', to: 'pages#company', as: :company_landing
  # so we call on the Company method from Pages Controller.
  # HTML'e baktiginda company.html.erb goreceksin same name as the method.
  # pages path, company action.
end

app/models/work_experience.rb
class WorkExperience < ApplicationRecord
  belongs_to :employee

  validates :industry,    presence: true
  validates :experience,  presence: true
  validates :company,     presence: true
  validates :title,       presence: true
  validates :description, presence: true
  validates :start_date,  presence: true
  validates :end_date,    presence: true

  def duration
    if self.end_date && self.start_date
      (( self.end_date - self.start_date ).to_i / 365 )
    else
      0
    end
  end
end

app/controllers/company/account/job_applications_controller.rb
class Company::Account::JobApplicationsController < Company::BaseController

  def show
    @job_application = JobApplication.find(params[:id])
    @job_application.read_at = Time.now
    @job_application.save!
    @job = @job_application.job_offer
  end

  def accept
    @job_application = JobApplication.find(params[:id])
    @job_application.update(status: "accepted")
    redirect_to company_account_job_application_path(@job_application)
  end

  def decline
    @job_application = JobApplication.find(params[:id])
    @job_application.update(status: "declined")
    redirect_to company_account_job_application_path(@job_application)
  end

end

app/controllers/company/account/jobs_controller.rb
class Company::Account::JobsController < Company::BaseController
    before_action :set_job_offer, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = current_company.job_offers
  end

  def show
    @job.job_applications.each do |job_application|
      job_application.update(read_at: Time.now)
    end
  end

  def new
    @job = JobOffer.new
  end

  def create
    @job = JobOffer.new(job_params)
    @job.company = current_company
    @job.save
    redirect_to company_account_profile_path(current_company)
  end

  def edit
  end

  def update
     if @job.update(job_params)
      redirect_to company_account_root_path
    else
      flash[:alert1] = "Please fill all the required fields."
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to company_account_profile_path
  end

  private

  def job_params
    params.require(:job_offer).permit(:name, :city, :event, :start_date, :end_date, :address, :wage, :job_description, :photo, :photo_cache)
  end

  def set_job_offer
    @job = current_company.job_offers.find(params[:id])
  end

end

app/controllers/company/account/profiles_controller.rb
class Company::Account::ProfilesController < Company::BaseController
  before_action :set_profile

  def show
    @job_offers = current_company.job_offers.order(created_at: :desc).limit(3)
    @job_applications = current_company.job_applications.order(created_at: :desc)
    get_suggested_employees
    @industry = []
    @suggested_employees.each do |suggested_employee|
      suggested_employee.work_experiences.each do |work|
          @industry << work.industry
       end
     end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to company_account_profile_path
    else
      flash[:alert1] = "Please fill all the required fields."
      render :edit
    end
  end

  private

  def set_profile
    @profile = current_company
  end

  def profile_params
    params.require(:company).permit(:name, :industry, :description, :photo, :photo_cache)
  end

  def get_suggested_employees
   #  @suggested_employees = []
   #  Employee.all.each do |employee|
   #    employee.work_experiences.each do |work_experience|
   #      if work_experience.industry == current_company.industry
   #        @suggested_employees << employee
   #      end
   #    end
   #  end
   # @suggested_employees = @suggested_employees.uniq
   @suggested_employees = Employee.all.select { |employee| employee.first_name != "Hey"}
  end
end

app/controllers/contractor/account/job_applications_controller.rb
class Contractor::Account::JobApplicationsController < Contractor::BaseController
  def index
    @job_applications = current_employee.job_applications
  end
end

app/controllers/contractor/account/profiles_controller.rb
class Contractor::Account::ProfilesController < Contractor::BaseController
  before_action :set_profile

  def show
    @job_applications = current_employee.job_applications.order('created_at DESC').limit(6)
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to contractor_account_profile_path
    else
      flash[:alert1] = "Fill all the required fields"
      render :edit
    end
  end

  private

  def profile_params
    params.require(:employee).permit(:first_name, :last_name, :age, :gender, :location, :availability, :photo, :photo_cache)
  end

  def set_profile
    @profile = current_employee
  end

end

app/controllers/contractor/account/work_experiences_controller.rb
class Contractor::Account::WorkExperiencesController < Contractor::BaseController
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]

  def index
    @work_experiences = WorkExperience.where(employee_id: current_employee.id).order(created_at: :desc)
  end

  def show
    @work_experiences = current_employee.work_experiences
  end

  def new
    @work_experience = WorkExperience.new
  end

  def create
    @work_experience = WorkExperience.new(work_experience_params)
    @work_experience.employee = current_employee
    if @work_experience.save
      redirect_to contractor_account_work_experiences_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @work_experience.update(work_experience_params)
      redirect_to contractor_account_work_experiences_path
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def work_experience_params
    params.require(:work_experience).permit(:industry, :experience, :company, :title, :time, :description, :start_date, :end_date)
  end

  def set_work_experience
    @work_experience = WorkExperience.find(params[:id])
  end

end

app/views/contractor/account/work_experiences/edit.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'nyc_try.png' %>);">
  <div class="banner-content">
    <h2>Add a new work experience</h2>
    <h3>
      <em></em>
    </h3>
  </div>
</div>

<div class="wrapper-grey">
  <div class="container">
    <div class="row">

      <div class="col-md-7 col-xs-12">
        <div class="box2">
          <%= simple_form_for @work_experience, url: contractor_account_work_experience_path(@work_experience), method: :put, class:"panel panel-default" do |f| %>
            <%= f.input :industry %>
            <%= f.input :experience %>
            <%= f.input :company %>
            <%= f.input :title %>
            <%= f.input :start_date %>
            <%= f.input :end_date %>
            <%= f.input :description %>
            <%= f.submit %>
          <% end %>
        </div>     
      </div>
    </div>
  </div>
</div>

app/views/contractor/account/work_experiences/index.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <h1 class="display-3">Hello, <%= current_employee.first_name %></h1>
      <p class="lead">Your current and past work experience</p>

      <div class="application-status-actions">
        <p class="lead">
          <%= link_to contractor_account_profile_path, class:"btn btn-primary" do %>
          <i class="fa fa-arrow-left fa-1x" aria-hidden="true"></i>
        <% end %>
          <%= link_to "Add work experience", new_contractor_account_work_experience_path, method: :get, class:"btn btn-primary btn-sm" %>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <% @work_experiences.each do |work_experience| %>
    <div class="col-xs-4">
      <div class="card card-block card-even-smaller">
      <%= link_to contractor_account_work_experience_path(work_experience) do %>
        <h4 class="card-title">
        <%= work_experience.title %>
        </h4>
        <% end %>
        <p class="card-text">
          <strong>Company:</strong> <%= work_experience.company %>
        </p>
        <p class="card-text">
          <strong>Industry:</strong> <%= work_experience.industry %>
        </p>
        <p class="card-text">
         <strong>Duration:</strong> <%= work_experience.duration %> years
       </p>
       <p class="card-text">
         <strong>Description:</strong> <%= work_experience.description %>
       </p>

     </div>
   </div>
   <% end %>
 </div>
</div>

app/views/contractor/account/work_experiences/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'nyc_try.png' %>);">
  <div class="banner-content">
    <h2>Add new work experience</h2>
    <h3>
      <em><%= link_to contractor_account_profile_path do %><i class="fa fa-arrow-left fa-1x" aria-hidden="true"></i>
      <% end %></em>
    </h3>
  </div>
</div>

<div class="wrapper-grey">
  <div class="container">
    <div class="row">

      <div class="col-md-7 col-xs-12">
        <div class="box2">
          <%= simple_form_for @work_experience, url: contractor_account_work_experiences_path, method: :post, class:"panel panel-default" do |f| %>
            <%= f.input :industry %>
            <%= f.input :experience %>
            <%= f.input :company %>
            <%= f.input :title %>
            <%= f.input :start_date %>
            <%= f.input :end_date %>
            <%= f.input :description %>
            <%= f.submit %>
          <% end %>
        </div>     
      </div>
    </div>
  </div>
</div>

app/views/contractor/account/work_experiences/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'nyc_try.png' %>);">
  <div class="banner-content">
    <h2>Work Experience</h2>
  </div>
</div>
<div class="wrapper-grey">
  <div class="container">
    <div class="row">

      <div class="col-md-8 col-md-offset-2 col-xs-12">
        <div class="box2">
            <table class="table">
              <tbody>
                <tr>
                  <td><em>Industry:</em></td>
                  <td><%= @work_experience.industry %></td>
                </tr>
                <tr>
                  <td><em>Experience:</em></td>
                  <td><%= @work_experience.experience %></td>
                </tr>
                <tr>
                <td><em>Company:</em></td>
                  <td><%= @work_experience.company %></td>
                </tr>
                <tr>
                  <td><em>Title:</em></td>
                  <td><%= @work_experience.title %></td>
                </tr>
                <tr>
                  <td><em>Start Date:</em></td>
                  <td><%= @work_experience.start_date %></td>
                </tr>
                <tr>
                  <td><em>End Date:</em></td>
                  <td><%= @work_experience.end_date %></td>
                </tr>
                <tr>
                        <tr>
                  <td><em>Duration:</em></td>
                  <td><%= @work_experience.duration %> years</td>
                </tr>
                <tr>
                  <td><em>Description:</em></td>
                  <td><%= @work_experience.description %></td>
                </tr>
                <tr>
                  <td>Edit your profile:</td>
                    <td><%= link_to contractor_account_work_experiences_path do %><i class="fa fa-arrow-left fa-1x" aria-hidden="true"></i>
                    <% end %>
                  <em><%= link_to 'Edit', edit_contractor_account_work_experience_path(@work_experience), class: "btn btn-secondary", id: "edit-button", style:"text-decoration:none" %></em>
                  </td>
                </tr>
              </tbody>
            </table>
        </div>     
      </div>

    </div>
  </div>
</div>