config/routes.rb
Rails.application.routes.draw do
  # is it companies and amployees or contractor and company
  devise_for :companies,  controllers: { registrations: 'company/registrations', sessions: 'company/sessions' }
  devise_for :employees, controllers: { omniauth_callbacks: 'contractor/omniauth_callbacks', sessions: 'contractor/sessions' }
  resources :contractors, only: [:show]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :contractor do
    root to: 'cities#index', as: :root

    namespace :account do
      resource :profile, only: [:show, :edit, :update]
      resources :work_experiences, only: [:index, :new, :create, :show, :edit, :update]
      resources :job_applications, only: [:index]
    end

    resources :jobs, only: [:index, :show] do
      resources :job_applications, only: [:new, :create]
    end
  end

  namespace :company do
    root to: 'account/profiles#show', as: :root

    namespace :account do
      root to: 'profiles#show', as: :root

      resource :profile, only: [:show, :edit, :update]

      resources :jobs
      # ALL hence only: [:index, :show, :new, :create, :edit, :update, :destroy]

      resources :job_applications, only: [:show] do
        member do
          patch :accept
          patch :decline
        end
      end
    end
  end

  # static pages
  get '/i-am-a-company', to: 'pages#company', as: :company_landing
  # so we call on the Company method from Pages Controller.
  # HTML'e baktiginda company.html.erb goreceksin same name as the method.
  # pages path, company action.
end

app/views/shared/_flashes.html.erb
  <% if flash[:notice] %>
    <div class="alert alert-info fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert1] && params[:action] != "home" %>
    <div class="alert alert-error fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:alert1] %>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <!-- Logo -->
      <%= link_to root_path, class: "navbar-brand" do %>
      <% "MATCHER" %>
      <% end %>
    </div>

    <div class='collapse navbar-collapse' id="myNavbar">

      <ul class='nav navbar-nav navbar-right'>
        <% if current_employee.nil? && current_company.nil? %>
          <li><%= link_to 'Log in as an employee', new_employee_session_path %></li>
          <li><%= link_to 'Log in as a company', new_company_session_path %></li>
        <% end %>


        <% unless params[:controller] == "pages" && params[:action] == "home" %>
        <% unless current_employee.nil? || current_company.nil?  %>

        <li>
           <%= link_to "Companies",company_landing_path %>
        </li>
        <li>
          <%= link_to "Employees",contractor_root_path %>
        </li>
        <% end %>

        <% if employee_signed_in? || company_signed_in? %>
         <% if employee_signed_in? %>
        <li>
          <%= link_to contractor_account_profile_path do  %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <% elsif company_signed_in? %>
          <li>
          <%= link_to company_account_profile_path do  %>
          <i class="fa fa-building"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>

        <% else %>
        <li>
          <%= link_to company_account_profile_path do  %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <% end %>
        <% else %>
  <% if (params[:controller] == "pages" && params[:action] == "company")|| params[:controller] == "company/registrations" %>

        <li>
          <%#= link_to t(".sign_in", default: "Login"), new_company_session_path %>
        </li>
        <% elsif (params[:controller] == "pages" && params[:action] == "company")|| params[:controller] == "employee/registrations" %>

        <li>
          <%#= link_to t(".sign_in", default: "Login"), new_employee_session_path %>
        </li>

  <% end %>
        <% end %>
      <% end %>
       <% if employee_signed_in? || company_signed_in? %>
          <% if employee_signed_in? %>

            <li>
              <%= link_to destroy_employee_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>

            <% else %>

            <li>
              <%= link_to destroy_company_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>