config/routes.rb
Rails.application.routes.draw do
  # is it companies and amployees or contractor and company
  devise_for :companies,  controllers: { registrations: 'company/registrations', sessions: 'company/sessions' }
  devise_for :employees, controllers: { omniauth_callbacks: 'contractor/omniauth_callbacks', sessions: 'contractor/sessions' }
  resources :contractors, only: [:show]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :contractor do
    root to: 'cities#index', as: :root

    namespace :account do
      resource :profile, only: [:show, :edit, :update]
      resources :work_experiences, only: [:index, :new, :create, :show, :edit, :update]
      resources :job_applications, only: [:index]
    end

    resources :jobs, only: [:index, :show] do
      resources :job_applications, only: [:new, :create]
    end
  end

  namespace :company do
    root to: 'account/profiles#show', as: :root

    namespace :account do
      root to: 'profiles#show', as: :root

      resource :profile, only: [:show, :edit, :update]

      resources :jobs
      # ALL hence only: [:index, :show, :new, :create, :edit, :update, :destroy]

      resources :job_applications, only: [:show] do
        member do
          patch :accept
          patch :decline
        end
      end
    end
  end

  # static pages
  get '/i-am-a-company', to: 'pages#company', as: :company_landing
  # so we call on the Company method from Pages Controller.
  # HTML'e baktiginda company.html.erb goreceksin same name as the method.
  # pages path, company action.
end

app/controllers/company/account/job_applications_controller.rb
class Company::Account::JobApplicationsController < Company::BaseController

  def show
    @job_application = JobApplication.find(params[:id])
    @job_application.read_at = Time.now
    @job_application.save!
    @job = @job_application.job_offer
  end

  def accept
    @job_application = JobApplication.find(params[:id])
    @job_application.update(status: "accepted")
    redirect_to company_account_job_application_path(@job_application)
  end

  def decline
    @job_application = JobApplication.find(params[:id])
    @job_application.update(status: "declined")
    redirect_to company_account_job_application_path(@job_application)
  end

end

app/controllers/company/account/jobs_controller.rb
class Company::Account::JobsController < Company::BaseController
    before_action :set_job_offer, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = current_company.job_offers
  end

  def show
    @job.job_applications.each do |job_application|
      job_application.update(read_at: Time.now)
    end
  end

  def new
    @job = JobOffer.new
  end

  def create
    @job = JobOffer.new(job_params)
    @job.company = current_company
    @job.save
    redirect_to company_account_profile_path(current_company)
  end

  def edit
  end

  def update
     if @job.update(job_params)
      redirect_to company_account_root_path
    else
      flash[:alert1] = "Please fill all the required fields."
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to company_account_profile_path
  end

  private

  def job_params
    params.require(:job_offer).permit(:name, :city, :event, :start_date, :end_date, :address, :wage, :job_description, :photo, :photo_cache)
  end

  def set_job_offer
    @job = current_company.job_offers.find(params[:id])
  end

end

app/controllers/company/account/profiles_controller.rb
class Company::Account::ProfilesController < Company::BaseController
  before_action :set_profile

  def show
    @job_offers = current_company.job_offers.order(created_at: :desc).limit(3)
    @job_applications = current_company.job_applications.order(created_at: :desc)
    get_suggested_employees
    @industry = []
    @suggested_employees.each do |suggested_employee|
      suggested_employee.work_experiences.each do |work|
          @industry << work.industry
       end
     end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to company_account_profile_path
    else
      flash[:alert1] = "Please fill all the required fields."
      render :edit
    end
  end

  private

  def set_profile
    @profile = current_company
  end

  def profile_params
    params.require(:company).permit(:name, :industry, :description, :photo, :photo_cache)
  end

  def get_suggested_employees
   #  @suggested_employees = []
   #  Employee.all.each do |employee|
   #    employee.work_experiences.each do |work_experience|
   #      if work_experience.industry == current_company.industry
   #        @suggested_employees << employee
   #      end
   #    end
   #  end
   # @suggested_employees = @suggested_employees.uniq
   @suggested_employees = Employee.all.select { |employee| employee.first_name != "Hey"}
  end
end

app/controllers/contractor/account/job_applications_controller.rb
class Contractor::Account::JobApplicationsController < Contractor::BaseController
  def index
    @job_applications = current_employee.job_applications
  end
end

app/controllers/contractor/account/profiles_controller.rb
class Contractor::Account::ProfilesController < Contractor::BaseController
  before_action :set_profile

  def show
    @job_applications = current_employee.job_applications.order('created_at DESC').limit(6)
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to contractor_account_profile_path
    else
      flash[:alert1] = "Fill all the required fields"
      render :edit
    end
  end

  private

  def profile_params
    params.require(:employee).permit(:first_name, :last_name, :age, :gender, :location, :availability, :photo, :photo_cache)
  end

  def set_profile
    @profile = current_employee
  end

end

app/controllers/contractor/account/work_experiences_controller.rb
class Contractor::Account::WorkExperiencesController < Contractor::BaseController
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]

  def index
    @work_experiences = WorkExperience.where(employee_id: current_employee.id).order(created_at: :desc)
  end

  def show
    @work_experiences = current_employee.work_experiences
  end

  def new
    @work_experience = WorkExperience.new
  end

  def create
    @work_experience = WorkExperience.new(work_experience_params)
    @work_experience.employee = current_employee
    if @work_experience.save
      redirect_to contractor_account_work_experiences_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @work_experience.update(work_experience_params)
      redirect_to contractor_account_work_experiences_path
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def work_experience_params
    params.require(:work_experience).permit(:industry, :experience, :company, :title, :time, :description, :start_date, :end_date)
  end

  def set_work_experience
    @work_experience = WorkExperience.find(params[:id])
  end

end

app/controllers/contractor/profiles_controller.rb
class Contractor::ProfilesController < ApplicationController
  before_action :authenticate_employee!
  before_action :set_profile

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_contractor_profile_path
    else
      flash[:alert] = "Fill all the required fields"
      render :edit
    end
  end

  private

  def profile_params
    params.require(:employee).permit(:first_name, :last_name, :age, :gender, :location, :availability)
  end

  def set_profile
    @profile = current_employee
  end

end

app/views/company/account/profiles/edit.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'nyc_try.png' %>);">
  <div class="banner-content">
    <h2>Edit your company profile</h2>
    <h3>
      <em></em>
    </h3>
  </div>
</div>

<div class="wrapper-grey">
  <div class="container">
    <div class="row">

      <div class="col-xs-12">
        <div class="box2">
          <%= simple_form_for @profile, url:company_account_profile_path(@profile) do |f|  %>
            <%= f.input :name, required: true %>
            <%= f.input :industry, required: true %>
            <%= f.input :description, required: true %>
            <%= f.input :email, required: true %>
            <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
            <%= f.input :photo %> <%= f.input :photo_cache, as: :hidden %> <%= f.submit %>
          <% end %>
        </div>     
      </div>
    </div>
  </div>
</div>

app/views/company/account/profiles/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'nyc_try.png' %>);">
  <div class="banner-content">
    <h2>Welcome to your company profile <%= current_company.name %></h2>
  </div>
</div>

<div class="container anchor">
  <div class="row">

    <div class="col-sm-4">
      <div class="log-picture">
        <%= image_tag current_company.photo, class: "button-card" %>
      </div>
    </div>

    <div class="col-sm-4">
      <table class="table">
        <tbody>
          <tr>
            <th>PROFILE DETAILS</th>
          </tr>
          <tr>
            <td><em>Name:</em></td>
            <td><%= current_company.name %></td>
          </tr>
          <tr>
            <td><em>Industry:</em></td>
            <td><%= current_company.industry %></td>
          </tr>
          <tr>
            <td><em>Description:</em></td>
            <td><%= current_company.description %></td>
          </tr>
          <tr>
            <td>Edit your profile:</td>
            <td><em><%= link_to 'Edit', edit_company_account_profile_path(@job), class: "btn btn-secondary", id: "edit-button", style:"text-decoration:none" %></em></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-sm-4">
      <div>
        <ul class="list-unstyled">
          <li>
            <%= link_to "Add Job Offer",new_company_account_job_path, class: "btn btn-block btn-primary btn-lg  add-job-offer" %>
          </li>
          <li>
            <%= link_to "See All Offers", company_account_jobs_path, class: "btn btn-default  btn-primary btn-lg add-job-offer" %>

          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- job offers cards -->
  <div class="row">
    <div class="bootstrap-demo">
      <%  @job_offers.each do |job_offer| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card">
          <%= job_offer.photo.present? ? cl_image_tag(job_offer.photo, class:"card-img-top", height: 494, width: 623, crop: :fill) : image_tag('01_city.jpg') %>
          <div class="card-block">

            <h4 class="card-title">Position: <%= job_offer.name %></h4>
            <p class="card-text">City: <%= job_offer.city %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= unread_job_offer_applications_count(job_offer) %> New Applicants</li>
            <li class="list-group-item"><%= job_offer.job_applications.count %> Applicants</li>
          </ul>
          <%= link_to "See Applicants", company_account_job_path(job_offer), class: "card-link btn btn-primary btn-padding"%>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <!-- suggested_employee -->
  <% unless @suggested_employees.empty? %>
    <div class="row ">
      <div class="bootstrap-demo">
        <h3 class="text-center anchor">
          Suggested Employees
        </h3>
          <% @suggested_employees.each do |suggested_employee| %>
            <div class="col-xs-12 col-sm-4">
              <div class="card card-smaller">
                <% if suggested_employee.provider == 'linkedin' %>
                  <%= cl_image_tag suggested_employee.linkedin_photo_url, crop: :fill %>
                <% else  %>
                  <%= cl_image_tag suggested_employee.photo, crop: :fill %>
                <% end %>
                <div class="card-block">
                  <div class="card-title">
                    Name: <%= suggested_employee.first_name %>
                  </div>
                  <h4 class="card-text">
                    Industry: <%= current_company.industry %>
                   </h4>
                   <p>
                    <%#= link_to 'See profile', company_account_job_applications_path(job_applications), class: 'btn btn-primary' %>
                   </p>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  <% end %>
</div>