config/routes.rb
Rails.application.routes.draw do
  # is it companies and amployees or contractor and company
  devise_for :companies,  controllers: { registrations: 'company/registrations', sessions: 'company/sessions' }
  devise_for :employees, controllers: { omniauth_callbacks: 'contractor/omniauth_callbacks', sessions: 'contractor/sessions' }
  resources :contractors, only: [:show]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :contractor do
    root to: 'cities#index', as: :root

    namespace :account do
      resource :profile, only: [:show, :edit, :update]
      resources :work_experiences, only: [:index, :new, :create, :show, :edit, :update]
      resources :job_applications, only: [:index]
    end

    resources :jobs, only: [:index, :show] do
      resources :job_applications, only: [:new, :create]
    end
  end

  namespace :company do
    root to: 'account/profiles#show', as: :root

    namespace :account do
      root to: 'profiles#show', as: :root

      resource :profile, only: [:show, :edit, :update]

      resources :jobs
      # ALL hence only: [:index, :show, :new, :create, :edit, :update, :destroy]

      resources :job_applications, only: [:show] do
        member do
          patch :accept
          patch :decline
        end
      end
    end
  end

  # static pages
  get '/i-am-a-company', to: 'pages#company', as: :company_landing
  # so we call on the Company method from Pages Controller.
  # HTML'e baktiginda company.html.erb goreceksin same name as the method.
  # pages path, company action.
end

app/controllers/company/account/job_applications_controller.rb
class Company::Account::JobApplicationsController < Company::BaseController

  def show
    @job_application = JobApplication.find(params[:id])
    @job_application.read_at = Time.now
    @job_application.save!
    @job = @job_application.job_offer
  end

  def accept
    @job_application = JobApplication.find(params[:id])
    @job_application.update(status: "accepted")
    redirect_to company_account_job_application_path(@job_application)
  end

  def decline
    @job_application = JobApplication.find(params[:id])
    @job_application.update(status: "declined")
    redirect_to company_account_job_application_path(@job_application)
  end

end

app/controllers/company/account/jobs_controller.rb
class Company::Account::JobsController < Company::BaseController
    before_action :set_job_offer, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = current_company.job_offers
  end

  def show
    @job.job_applications.each do |job_application|
      job_application.update(read_at: Time.now)
    end
  end

  def new
    @job = JobOffer.new
  end

  def create
    @job = JobOffer.new(job_params)
    @job.company = current_company
    @job.save
    redirect_to company_account_profile_path(current_company)
  end

  def edit
  end

  def update
     if @job.update(job_params)
      redirect_to company_account_root_path
    else
      flash[:alert1] = "Please fill all the required fields."
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to company_account_profile_path
  end

  private

  def job_params
    params.require(:job_offer).permit(:name, :city, :event, :start_date, :end_date, :address, :wage, :job_description, :photo, :photo_cache)
  end

  def set_job_offer
    @job = current_company.job_offers.find(params[:id])
  end

end

app/controllers/company/account/profiles_controller.rb
class Company::Account::ProfilesController < Company::BaseController
  before_action :set_profile

  def show
    @job_offers = current_company.job_offers.order(created_at: :desc).limit(3)
    @job_applications = current_company.job_applications.order(created_at: :desc)
    get_suggested_employees
    @industry = []
    @suggested_employees.each do |suggested_employee|
      suggested_employee.work_experiences.each do |work|
          @industry << work.industry
       end
     end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to company_account_profile_path
    else
      flash[:alert1] = "Please fill all the required fields."
      render :edit
    end
  end

  private

  def set_profile
    @profile = current_company
  end

  def profile_params
    params.require(:company).permit(:name, :industry, :description, :photo, :photo_cache)
  end

  def get_suggested_employees
   #  @suggested_employees = []
   #  Employee.all.each do |employee|
   #    employee.work_experiences.each do |work_experience|
   #      if work_experience.industry == current_company.industry
   #        @suggested_employees << employee
   #      end
   #    end
   #  end
   # @suggested_employees = @suggested_employees.uniq
   @suggested_employees = Employee.all.select { |employee| employee.first_name != "Hey"}
  end
end

app/controllers/contractor/account/job_applications_controller.rb
class Contractor::Account::JobApplicationsController < Contractor::BaseController
  def index
    @job_applications = current_employee.job_applications
  end
end

app/controllers/contractor/account/profiles_controller.rb
class Contractor::Account::ProfilesController < Contractor::BaseController
  before_action :set_profile

  def show
    @job_applications = current_employee.job_applications.order('created_at DESC').limit(6)
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to contractor_account_profile_path
    else
      flash[:alert1] = "Fill all the required fields"
      render :edit
    end
  end

  private

  def profile_params
    params.require(:employee).permit(:first_name, :last_name, :age, :gender, :location, :availability, :photo, :photo_cache)
  end

  def set_profile
    @profile = current_employee
  end

end

app/controllers/contractor/account/work_experiences_controller.rb
class Contractor::Account::WorkExperiencesController < Contractor::BaseController
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]

  def index
    @work_experiences = WorkExperience.where(employee_id: current_employee.id).order(created_at: :desc)
  end

  def show
    @work_experiences = current_employee.work_experiences
  end

  def new
    @work_experience = WorkExperience.new
  end

  def create
    @work_experience = WorkExperience.new(work_experience_params)
    @work_experience.employee = current_employee
    if @work_experience.save
      redirect_to contractor_account_work_experiences_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @work_experience.update(work_experience_params)
      redirect_to contractor_account_work_experiences_path
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def work_experience_params
    params.require(:work_experience).permit(:industry, :experience, :company, :title, :time, :description, :start_date, :end_date)
  end

  def set_work_experience
    @work_experience = WorkExperience.find(params[:id])
  end

end

app/controllers/contractor/jobs_controller.rb
class Contractor::JobsController < Contractor::BaseController
  skip_before_action :authenticate_employee!

  #list all the job offer
  def index
    @jobs = JobOffer.all

    if params[:location].present?
      @jobs = @jobs.where(city: params[:location])
    end
  end

  def show

    @job = JobOffer.find(params[:id])
    @job_coordinates = { lat:  @job.latitude, lng: @job.longitude }

    # @jobs = JobOffer.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@job) do |job, marker|
      marker.lat job.latitude
      marker.lng job.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end
end

app/views/company/account/jobs/edit.html.erb
<div class="container anchor">
  <div class="row">
    <div class="col-xs-12 offset-1">
      <%= simple_form_for @job, url: company_account_job_path do |f| %>
        <%= f.input :name %>
        <%= f.input :event %>
        <%= f.input :city %>
        <%= f.input :job_description %>
        <%= f.input :address %>
        <%= f.input :wage %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit 'Save Job Offer' %>
      <% end %>
    </div>
  </div>
</div>

app/views/company/account/jobs/index.html.erb
<div class="container">
  <div class="row anchor text-center">
    <div class="col-xs-12">
      <%= link_to "Back", company_account_profile_path, class: "btn btn-primary btn-lg see-all-offers" %>
    </div>
  </div>
  <div class="row anchor">
  <h2 class="text-center">Current and Past Job Offers</h2>
      <div class="bootstrap-demo">
        <%  @jobs.each do |job| %>
          <div class="col-xs-12 col-sm-4">
            <div class="card">
              <%= job.photo.present? ? cl_image_tag(job.photo, class:"card-img-top", height: 494, width: 623, crop: :fill) : image_tag('01_city.jpg') %>
              <div class="card-block">
                <h4 class="card-title">Position: <%= job.name %></h4>
                <p class="card-text">City: <%= job.city %></p>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><%= job.job_applications.count %> Applicants</li>
              </ul>
              <div class="card-block">
                <%= link_to "See Applicants", company_account_job_path(job), class: "card-link btn btn-primary"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/company/account/jobs/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(https://unsplash.it/1024/600/?job);">
  <div class="banner-content">
    <h2>Add your job offer</h2>
    <h3>
      <em></em>
    </h3>
  </div>
</div>

<div class="wrapper-grey">
  <div class="container">
    <div class="row">

      <div class="col-xs-12">
        <div class="edit-profile-card">
          <%= simple_form_for @job, url: company_account_jobs_path, class:"panel panel-default" do |f| %>
            <%= f.input :name %>
            <%= f.input :event %>
            <%= f.input :city %>
            <%= f.input :job_description %>
            <%= f.input :address %>
            <%= f.input :wage%>
            <%= f.input :start_date %>
            <%= f.input :end_date %>
             <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.submit 'Create Job Offer', class:"btn btn-primary" %>
          <% end %>
        </div>     
      </div>
    </div>
  </div>
</div>

app/views/company/account/jobs/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'nyc_try.png' %>);">
  <div class="banner-content">
<h2 class="anchor text-center"> <%= @job.name %> </h2>
<h4 class="text-center padding-bottom">You have <%= @job.job_applications.count %> applicants for this position</h4 >
  </div>
</div>

<div class="wrapper-grey">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
          <div class="box2">
            <div class="row">
              <div class="col-md-3">
                <p class="label-job">Event:</p>
              </div>
              <div class="col-md-9">
                <p class="data-job"><%= @job.event %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-3">
                <p class="label-job">Name:</p>
              </div>
              <div class="col-md-9">
                <p class="data-job"><%= @job.name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-3">
                <p class="label-job">City:</p>
              </div>
              <div class="col-md-9">
                <p class="data-job"><%= @job.city %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-3">
                <p class="label-job">Description :</p>
              </div>
              <div class="col-md-9">
                <p class="data-job"><%=@job.job_description%></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-3">
                <p class="label-job">Duration:</p>
              </div>
              <div class="col-md-9">
                <p class="data-job"><%=@job.start_date %> - <%= @job.end_date%> | <%=@job.duration%> days</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-3">
                <p class="label-job">Wage:</p>
              </div>
              <div class="col-md-9">
                <p class="data-job"><%= @job.wage %> $</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <p class="text-center">
                <%= link_to company_account_profile_path, class: 'btn btn-success' do %><i class="fa fa-arrow-left fa-1x" aria-hidden="true"></i>
                <% end %>
                <%= link_to 'Edit this job', edit_company_account_job_path, class: 'btn btn-success' %>
              </p>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>


<div class="container">
  <% if unread_job_offer_applications(@job).exists? %>
    <h3 class="text-center padding-bottom">List of new applicants</h3>
  <% end %>
    <div class="row">
      <% unread_job_offer_applications(@job).each do |job_application| %>
        <div class="col-xs-12 col-md-4">
            <div class="card">
            <% if job_application.employee.photo.file %>
              <%= cl_image_tag(job_application.employee.photo, crop: :fill, class: 'card-img-top') %>
            <% elsif job_application.employee.linkedin_photo_url %>
              <%= cl_image_tag(job_application.employee.linkedin_photo_url, crop: :fill, class: 'card-img-top') %>
            <% else %>
                <% if job_application.employee.gender == "male" %>
                  <%= image_tag ("fbppm.jpg") %>
                <% else %>
                  <%= image_tag ("fbppf.jpg") %>
                <% end %>
            <% end %>
              <div class="card-block">
                <h2 class="card-title"><%= job_application.employee.first_name %> <%= job_application.employee.last_name %> </h2>
                <h4 class="card-title">
                <% if job_application.employee.work_experiences.exists? %>
                  <span><%= job_application.employee.work_experiences.last.industry %> industry</span>
                <% end  %>
                </h4>
                <div class="meta">
                  <% if job_application.employee.work_experiences.exists? %>
                    <span><%= job_application.employee.work_experiences.last.experience %> years</span>
                  <% end  %>
                </div>
                <%= link_to 'See profile', company_account_job_application_path(job_application), class: 'btn btn-primary' %>
              </div>
            </div>
        </div>
      <% end %>
    </div>

    <h3 class="text-center padding-bottom">List of all applicants</h3>
    <div class="row">
      <% read_job_offer_applications(@job).each do |job_application| %>
          <div class="col-xs-12 col-md-4">
              <div class="card">
                <% if job_application.employee.photo.file %>
                  <%= cl_image_tag(job_application.employee.photo, crop: :fill, class: 'card-img-top') %>
                <% elsif job_application.employee.linkedin_photo_url %>
                  <%= cl_image_tag(job_application.employee.linkedin_photo_url, crop: :fill, class: 'card-img-top') %>
                <% else %>
                    <% if job_application.employee.gender == "male" %>
                      <%= image_tag ("fbppm.jpg") %>
                    <% else %>
                      <%= image_tag ("fbppf.jpg") %>
                    <% end %>
                <% end %>
              <div class="card-block">
                <h2 class="card-title"><%= job_application.employee.first_name %> <%= job_application.employee.last_name %> </h2>
                <h4 class="card-title">
                <% if job_application.employee.work_experiences.exists? %>
                  <span><%= job_application.employee.work_experiences.last.industry %> industry</span>
                <% end  %>
                </h4>
                <div class="meta">
                  <% if job_application.employee.work_experiences.exists? %>
                    <span><%= job_application.employee.work_experiences.last.experience %> years</span>
                  <% end  %>
                </div>
                <div class="card-block">
                  <%= link_to 'See profile', company_account_job_application_path(job_application), class: 'btn btn-primary' %>
                </div>
              </div>
              </div>
          </div>
      <% end %>
    </div>
</div>